version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test-app
    overwrite: yes

permissions:
  - object: / 
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: ec2-user