version: 0.2

phases:
  install:
    commands:
      - aws --version
      - docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l9d5m0q6)
      - npm install yarn
  build:
    commands:
      - docker build -t nest .
  post_build:
    commands:
      - docker tag nest:latest public.ecr.aws/l9d5m0q6/nest:latest
      - docker push public.ecr.aws/l9d5m0q6/nest:latest
      - echo Writing image definitions file...
      - printf '[{"name":"nest-container","imageUri":"%s"}]' 658986583341.dkr.ecr.ap-northeast-2.amazonaws.com/nest:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json