version: 0.2

phases:
  install:
    runtime-versions:
      docker: 23
    commands:
      - echo ======================= Installing packages =======================
  build:
    commands:
      - echo ======================= Build Starting =======================
      - docker-compose build
  post_build:
    commands:
      - echo ======================= Build Success =======================

artifacts:
  files: 
    - appspec.yml
    - '**/*'