version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm i yarn
  pre_build:
    commands:
      - echo Installing packages...
      - yarn
  build:
    commands:
      - echo Build Starting...
      - yarn build
  post_build:
    commands:
      - echo Build Success
      
artifacts:
  files: 
    - appspec.yml
    - '**/*'